### ISSUE TITLE
Potential memory leak with `Vector` members of entities

### ISSUE THREAD

**Issue by cemcebeci** [rl-language/rlc#4]
Running the fuzzer emitted for the following action:
```
import fuzzer.cpp_functions
import fuzzer.utils
import collections.vector

ent Entity:
    Vector<Int> member

fun has_loop():
    let i = 0
    while i < 10:
        let e : Entity
        i = i + 1

act play() -> Play:
    has_loop()
    act subact()
```

Finds a memory leak, with the message
```
Direct leak of 320 byte(s) in 10 object(s) allocated from:
    #0 0x4fb52f in malloc /home/ccebeci/rlc/rlc-infrastructure/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:68:3
    #1 0x53bc8a in rl_m_init__VectorTint64_tT_r_void (/home/ccebeci/rlc/rlc-infrastructure/rlc-debug/leaktest+0x53bc8a)
    #2 0x53b301 in rl_m_init__Entity (/home/ccebeci/rlc/rlc-infrastructure/rlc-debug/leaktest+0x53b301)
    #3 0x53c3d4 in rl_m__play_impl__Play_Play_shadow memory_leak.rl
    #4 0x53bfc8 in rl_fuzzer_fuzz_action_function_ (/home/ccebeci/rlc/rlc-infrastructure/rlc-debug/leaktest+0x53bfc8)
    #5 0x7f2af555446b in LLVMFuzzerTestOneInput /home/ccebeci/rlc/rlc-infrastructure/rlc/lib/fuzzer/src/fuzz_target.cpp:99:5
    #6 0x449513 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /home/ccebeci/rlc/rlc-infrastructure/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:614:13
    #7 0x44a800 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile>>&) /home/ccebeci/rlc/rlc-infrastructure/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:807:3
    #8 0x44aed2 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile>>&) /home/ccebeci/rlc/rlc-infrastructure/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:867:3
    #9 0x438e86 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /home/ccebeci/rlc/rlc-infrastructure/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:914:6
    #10 0x462ff2 in main /home/ccebeci/rlc/rlc-infrastructure/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #11 0x7f2af531dd8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: c289da5071a3399de893d2af81d6a30c62646e1e)
```

**Comment by drblallo** [comment]
fixed by 8891d5d
